version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: leadership-training-db
    environment:
      POSTGRES_DB: leadership_training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Use 5433 on host to avoid local conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: leadership-training-backend
    environment:
      NODE_ENV: development
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: leadership_training
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      JWT_SECRET: your-jwt-secret-key-change-in-production
      PORT: 3001
      # QR Code Configuration
      QR_CLOUD_API_URL: https://qrcodes.at/api
      QR_CLOUD_API_KEY: ${QR_CLOUD_API_KEY:-your_api_key_here}
      QR_CODE_ERROR_CORRECTION: M
      QR_CODE_SIZE: 300x300
      QR_CODE_FORMAT: PNG
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: https://api.openai.com/v1
      OPENAI_MODEL: gpt-4o-mini
      OPENAI_MAX_TOKENS: 2500
      OPENAI_TEMPERATURE: 0.7
      OPENAI_TIMEOUT_MS: 30000
      OPENAI_MAX_RETRIES: 3
      # Feature Flags & Analytics
      ENABLE_VARIANT_GENERATION_V2: ${ENABLE_VARIANT_GENERATION_V2:-false}
      VARIANT_GENERATION_ROLLOUT_PERCENTAGE: ${VARIANT_GENERATION_ROLLOUT_PERCENTAGE:-0}
      LOG_VARIANT_SELECTIONS: ${LOG_VARIANT_SELECTIONS:-true}
      GOOGLE_ANALYTICS_ID: ${GOOGLE_ANALYTICS_ID:-}
      # RAG Configuration
      RAG_API_URL: ${RAG_API_URL:-http://rag-service:8000}
      RAG_TIMEOUT_MS: ${RAG_TIMEOUT_MS:-10000}
      RAG_RETRY_ATTEMPTS: ${RAG_RETRY_ATTEMPTS:-1}
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      - ./config:/app/config
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: leadership-training-frontend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "3002:3000"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
